# Site settings
title: "Thomas Edgerton"
description: "This resume was created in one day."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Thomas Edgerton"
resume_title:                   "Technician"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "thomas.edgerton@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "1.916.276.4729"
resume_contact_address:         "352 Sawtell Rd, Roseville CA"

resume_header_contact_info:     "352 Sawtell Rd, Roseville CA • 1.916.276.4729 • thomas.edgerton@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Technician with vast IT experience. Skills include programming, networking, and de-mystifying the understandably overwealming world of IT.</p><p>I believe student-centric mastery based education is the key to preparing future generations for the challanges of today and tomorrow.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/LogosWorks"
  #resume_twitter_url:           "http://twitter.com/..."
  #resume_dribbble_url:          "https://dribbble.com/..."
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/..."
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://LogosWorks.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
